-- MySQL Script generated by MySQL Workbench
-- 07/22/16 13:51:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Peppe_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peppe_copy1` (
  `Angolo` INT NOT NULL,
  `Rigore` VARCHAR(45) NULL,
  PRIMARY KEY (`Angolo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peppe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peppe` (
  `Campo1` INT NOT NULL,
  `Campo2` VARCHAR(45) NULL,
  `Campo3` INT NOT NULL,
  PRIMARY KEY (`Campo1`, `Campo3`),
  INDEX `fk_Peppe_Peppe_copy1_idx` (`Campo3` ASC),
  CONSTRAINT `fk_Peppe_Peppe_copy1`
    FOREIGN KEY (`Campo3`)
    REFERENCES `mydb`.`Peppe_copy1` (`Angolo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
